# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFileDialog
from ForgeryDetection import Detect

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../PycharmProjects/DeteksiCopyMove/icons8-image-file-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgInput = QtWidgets.QLabel(self.centralwidget)
        self.imgInput.setGeometry(QtCore.QRect(10, 10, 512, 512))
        self.imgInput.setObjectName("imgInput")
        self.imgOutput = QtWidgets.QLabel(self.centralwidget)
        self.imgOutput.setGeometry(QtCore.QRect(530, 10, 512, 512))
        self.imgOutput.setObjectName("imgOutput")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(10, 540, 130, 40))
        self.btnLoad.setObjectName("btnLoad")
        self.btnDeteksi = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeteksi.setEnabled(False)
        self.btnDeteksi.setGeometry(QtCore.QRect(460, 540, 130, 40))
        self.btnDeteksi.setObjectName("btnDeteksi")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setEnabled(False)
        self.btnSave.setGeometry(QtCore.QRect(910, 540, 130, 40))
        self.btnSave.setObjectName("btnSave")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1050, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1050, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1050, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1050, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lblHeight = QtWidgets.QLabel(self.centralwidget)
        self.lblHeight.setGeometry(QtCore.QRect(1110, 10, 47, 13))
        self.lblHeight.setObjectName("lblHeight")
        self.lblWidth = QtWidgets.QLabel(self.centralwidget)
        self.lblWidth.setGeometry(QtCore.QRect(1110, 60, 47, 13))
        self.lblWidth.setObjectName("lblWidth")
        self.lblKeypoint = QtWidgets.QLabel(self.centralwidget)
        self.lblKeypoint.setGeometry(QtCore.QRect(1110, 120, 47, 13))
        self.lblKeypoint.setObjectName("lblKeypoint")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(1110, 170, 97, 13))
        self.lblStatus.setObjectName("lblStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.path = QtWidgets.QLabel(self.centralwidget)
        self.path.setObjectName("path")
        self.output = ''

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnLoad.clicked.connect(self.openImage)
        self.btnDeteksi.clicked.connect(self.detection)
        self.btnSave.clicked.connect(self.saveImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deteksi Copy-Move"))
        self.btnLoad.setText(_translate("MainWindow", "Load Image"))
        self.btnDeteksi.setText(_translate("MainWindow", "Deteksi"))
        self.btnSave.setText(_translate("MainWindow", "Save Image"))
        self.label.setText(_translate("MainWindow", "Height :"))
        self.label_2.setText(_translate("MainWindow", "Width :"))
        self.label_3.setText(_translate("MainWindow", "Keypoint :"))
        self.label_4.setText(_translate("MainWindow", "Status :"))
        self.lblHeight.setText(_translate("MainWindow", "-"))
        self.lblWidth.setText(_translate("MainWindow", "-"))
        self.lblKeypoint.setText(_translate("MainWindow", "-"))
        self.lblStatus.setText(_translate("MainWindow", "-"))

    def openImage(self):
        try:
            imagePath, _ = QFileDialog.getOpenFileName(MainWindow,"Load Image","E:\\CoMoFoD_small_v2\\","Image files (*.jpg *.jpeg *.png *.gif)")
            self.path.setText(imagePath)
            pixmap = QPixmap(imagePath)
            self.imgInput.setPixmap(pixmap)
            self.lblHeight.setText(str(pixmap.height()))
            self.lblWidth.setText(str(pixmap.width()))
            self.btnDeteksi.setEnabled(True)
        except:
            print("Load Image Error")

    def saveImage(self):
        try:
            name, _ = QFileDialog.getSaveFileName(MainWindow,"Load Image","result","png (*.png)")
            print(name)
            cv2.imwrite(name,self.output)
        except:
            print("Save Image Error")

    def detection(self):
        image=cv2.imread(self.path.text())
        detect=Detect(image)
        key_points,descriptors = detect.siftDetector()
        forgery = detect.locateForgery(20, 2)
        self.output = forgery
        self.lblKeypoint.setText(str(len(key_points)))
        if forgery is None:
            self.lblStatus.setText("Tidak Terdeteksi")
            qimage = QtGui.QImage(image.data, image.shape[1], image.shape[0],QtGui.QImage.Format_RGB888).rgbSwapped()
        else:
            self.lblStatus.setText("Terdeteksi")
            qimage = QtGui.QImage(forgery.data, forgery.shape[1], forgery.shape[0], QtGui.QImage.Format_RGB888).rgbSwapped()
        self.imgOutput.setPixmap(QtGui.QPixmap.fromImage(qimage))
        self.btnSave.setEnabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
